language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
 # - '3.7'
install:
  - pip install coveralls
  - pip install tox-travis
  - make
script:
  - make test
  - tox
notifications:
  email: false
after_success: coveralls