language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.5'
  - os: linux
    dist: trusty
    python: '3.6'
install:
  - "pip install ."
script: "python setup.py test"
notifications:
  email: false